### ISSUE TITLE
Windings function seems to corrupt the shape.

### ISSUE THREAD

**Issue by CodeMason** [ckohnert/msdfgen#1]
Specifically with the test example (./msdfgen msdf -font ARIALBD.TTF 'M' -o msdf.png -size 32 32 -pxrange 4 -autoframe -testrender render.png 1024 1024). Compiling on Linux (almost works, just a few tweaks) there are problems with commit 8b4f5f6b5d2932737ad4119e4c92f5acbc3dd528. 

I noticed that commenting out the realSign/medSign comparison (for msdf generation), fixes this problem. Ignoring how the font/svg is generated is probably the wrong way to go about it, but it works so far. I haven't gone beyond generating a MSDF for a single font glyph yet.

For reference (from main-line), this is what I see:
![msdf](https://user-images.githubusercontent.com/2230263/29232601-c3c3214e-7eec-11e7-9817-ee2bb3e4e5db.png)
![render](https://user-images.githubusercontent.com/2230263/29232602-c60a7be6-7eec-11e7-817d-358950028ed8.png)

As a result of commit 8b4f5f6b5d2932737ad4119e4c92f5acbc3dd528, this is what I see instead:
![msdf](https://user-images.githubusercontent.com/2230263/29232617-d72264d4-7eec-11e7-86a0-4bef914ade3d.png)
![render](https://user-images.githubusercontent.com/2230263/29232618-d9faccc8-7eec-11e7-9104-54b09df6e984.png)

**Comment by CodeMason** [comment]
If it helps, the shape export is
````
{
2.265625, 0;
c;
2.265625, 22.90625;
m;
9.1875, 22.90625;
y;
13.34375, 7.28125;
c;
17.453125, 22.90625;
m;
24.390625, 22.90625;
y;
24.390625, 0;
c;
20.09375, 0;
m;
20.09375, 18.03125;
y;
15.546875, 0;
c;
11.09375, 0;
m;
6.5625, 18.03125;
y;
6.5625, 0;
m;
#
}
````

**Comment by soimy** [comment]
Same here, any progress?
![hyheilizhitij regular 0](https://user-images.githubusercontent.com/1550237/29347122-d07cc406-827c-11e7-8d3d-88c383cba6c2.png)

**Comment by ckohnert** [comment]
I've not had a chance to look into this yet.

Also, @soimy, I'm not sure exactly what you're seeing in that one. It's hard to tell just from the msdf image whether it renders properly. Have you tried with the test render command line option?

**Comment by soimy** [comment]
@ckohnert I tried msdf/sdf sheet. Same result as @CodeMason screenshot. Main cause of these artifacts should be these black dots along-side glyph edge ( Maybe the fillRule error in Windspanner method?)
I will post more detail and way to represent these artifacts asap.

**Comment by ckohnert** [comment]
Found it. There was a silly truncation of the coordinate when calculating the winding spots. Fixed in 0367e0e

**Comment by ckohnert** [comment]
Thanks for the repro case by the way!

**Comment by soimy** [comment]
It works! Thanks @ckohnert 🍺
